#!/bin/sh

# sleep 0 && hyprpm reload -n
# (echo toor|sudo -S mount --bind /home/a/Downloads/waybind /home/a/.local/share/waydroid/data/media/0/Download/waybind/)

# Wob bar
(
  rm /tmp/wobpipe
  mkfifo /tmp/wobpipe
  tail -n 1 -f /tmp/wobpipe | wob
)&

# One serialized worker receives all display-brightness keypresses.
daemonize "$HOME/.config/hypr/scripts/brightness" start
daemonize "$HOME/.config/hypr/scripts/contrast" start

# Restore last brightness/contrast from disk
sleep 0.5  # let workers init their FIFOs
"$HOME/.config/hypr/scripts/brightness" restore
"$HOME/.config/hypr/scripts/contrast" restore

# This fixes something; maybe used to fix something
# (sleep 2 && xhost + local:)&

# Set env vars
(
  systemctl --user import-environment WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
  dbus-update-activation-environment --systemd WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP=Hyprland XDG_SESSION_TYPE=wayland
)&

echo
