[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "~/.local/bin/x-terminal-emulator start --class 'wezterm.scratchpad'"
class = "wezterm.scratchpad"
size = "90% 90%"
# position = "50% 50%"
